/* REelo Profile UX v1 */
(function(){
'use strict';
const p=document.getElementById('profile'); if(!p)return;
function style(){if(document.getElementById('reelo-profile-style'))return;const s=document.createElement('style');s.id='reelo-profile-style';s.textContent=`
.profile{background:linear-gradient(180deg,#101010,#080808)}.reelo-profile-tools{display:flex;gap:8px;margin-top:16px}.reelo-tool{flex:1;border:1px solid #333;background:#181818;color:#fff;border-radius:10px;padding:10px;font-weight:800;cursor:pointer}.reelo-tool:hover{background:#242424}.reelo-badge{display:inline-flex;align-items:center;gap:5px;margin-left:5px;font-size:11px;color:#aaa}.reelo-edit-sheet{position:fixed;inset:0;background:rgba(0,0,0,.72);display:none;align-items:flex-end;z-index:20}.reelo-edit-sheet.show{display:flex}.reelo-edit-box{width:100%;max-width:760px;margin:auto;background:#151515;border:1px solid #333;border-radius:20px 20px 0 0;padding:18px}.reelo-edit-box h2{margin:0 0 14px;font-size:18px}.reelo-edit-box label{display:block;font-size:11px;color:#888;margin:12px 0 6px}.reelo-edit-box input,.reelo-edit-box textarea{width:100%;border:1px solid #333;background:#090909;color:#fff;border-radius:10px;padding:11px;outline:none}.reelo-edit-box textarea{min-height:90px;resize:vertical}.reelo-edit-actions{display:flex;gap:8px;margin-top:14px}.reelo-edit-actions button{flex:1;border:0;border-radius:10px;padding:11px;font-weight:800}.reelo-save{background:#fff;color:#000}.reelo-cancel{background:#292929;color:#fff}.reelo-avatar-ring{padding:3px;border-radius:50%;background:linear-gradient(135deg,#fff,#555)}.reelo-avatar-ring .avatar{border:0}.reelo-count{font-size:10px;color:#777;margin-top:3px}
` ;document.head.appendChild(s)}
function openEdit(){if(document.getElementById('reelo-edit-sheet')){document.getElementById('reelo-edit-sheet').classList.add('show');return}const u=window.__reeloProfileData?.user;if(!u)return;const x=document.createElement('div');x.id='reelo-edit-sheet';x.className='reelo-edit-sheet show';x.innerHTML='<div class="reelo-edit-box"><h2>Edit profile</h2><label>Display name</label><input id="reelo-edit-name" maxlength="80" value="'+String(u.display_name||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')+'"><label>Bio</label><textarea id="reelo-edit-bio" maxlength="160">'+String(u.bio||'').replace(/</g,'&lt;')+'</textarea><div class="reelo-edit-actions"><button class="reelo-cancel" id="reelo-edit-cancel">Cancel</button><button class="reelo-save" id="reelo-edit-save">Save changes</button></div></div>';document.body.appendChild(x);document.getElementById('reelo-edit-cancel').onclick=()=>x.classList.remove('show');document.getElementById('reelo-edit-save').onclick=saveEdit}
async function saveEdit(){const u=window.__reeloProfileData?.user,t=localStorage.getItem('reelo_token');if(!t||!u)return;const btn=document.getElementById('reelo-edit-save');btn.disabled=true;try{const api=window.REELO_API||location.origin;const r=await fetch(api+'/api/me',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({display_name:document.getElementById('reelo-edit-name').value,bio:document.getElementById('reelo-edit-bio').value})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Could not update profile');window.__reeloProfileData.user=d.user;document.getElementById('reelo-edit-sheet').classList.remove('show');if(typeof window.renderProfile==='function')window.renderProfile();else location.reload()}catch(e){alert(e.message)}finally{btn.disabled=false}}
function enhance(){const d=window.__reeloProfileData;if(!d)return;const u=d.user;if(d.is_me){const actions=document.createElement('div');actions.className='reelo-profile-tools';actions.innerHTML='<button class="reelo-tool" id="reelo-edit">✎ Edit profile</button><button class="reelo-tool" onclick="location.href=\'settings.html\'">⚙ Settings</button>';p.appendChild(actions);document.getElementById('reelo-edit').onclick=openEdit}else{const old=document.getElementById('message');if(old)old.textContent='Message'} }
style();const original=window.renderProfile; if(original&&!original.__reeloWrapped){window.renderProfile=function(){original();setTimeout(enhance,0)};window.renderProfile.__reeloWrapped=true}const oldLoad=window.load;if(oldLoad&&!oldLoad.__reeloWrapped){window.load=function(){return oldLoad()};window.load.__reeloWrapped=true}setTimeout(()=>{if(window.data)window.__reeloProfileData=window.data;enhance()},500);
})();
