/* REelo Explore UI v1 — Instagram-style discovery */
(function(){
  'use strict';
  const API=window.REELO_API||'https://reelo-43rv.onrender.com';
  const q=document.getElementById('q');
  const content=document.getElementById('content');
  if(!q||!content)return;
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>{n=Number(n||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n)};
  const videoUrl=v=>v.filename?.startsWith('http')?v.filename:API+(v.filename?.startsWith('/')?'':'/')+v.filename;
  const demo=[
    ['🎵','music','Music & Sounds','12.4K posts'],['✨','fashion','Style & Fashion','8.7K posts'],['🎮','gaming','Gaming','7.2K posts'],['📸','photography','Photography','6.8K posts'],['💻','technology','Technology','5.9K posts'],['✈️','travel','Travel','4.6K posts']
  ];
  function style(){if(document.getElementById('reelo-explore-style'))return;const s=document.createElement('style');s.id='reelo-explore-style';s.textContent=`
  .reelo-explore-hero{padding:18px 0 8px}.reelo-explore-title{font-size:26px;font-weight:900;letter-spacing:-.03em}.reelo-explore-sub{color:#888;font-size:12px;margin-top:4px}.reelo-chips{display:flex;gap:8px;overflow:auto;padding:10px 0 12px;scrollbar-width:none}.reelo-chips::-webkit-scrollbar{display:none}.reelo-chip{border:1px solid #303030;background:#151515;color:#aaa;border-radius:999px;padding:8px 13px;font-size:12px;font-weight:800;white-space:nowrap}.reelo-chip.active{background:#fff;color:#000;border-color:#fff}.reelo-discover-title{display:flex;align-items:center;justify-content:space-between;margin:12px 0 8px}.reelo-discover-title b{font-size:14px}.reelo-discover-title span{font-size:11px;color:#777}.reelo-topics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.reelo-topic{min-height:72px;border:1px solid #242424;border-radius:14px;background:linear-gradient(145deg,#191919,#0e0e0e);color:#fff;text-align:left;padding:12px;cursor:pointer}.reelo-topic-icon{font-size:22px}.reelo-topic b{display:block;font-size:12px;margin-top:5px}.reelo-topic small{color:#777;font-size:10px}.reelo-explore-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;margin:0 -16px}.reelo-grid-item{position:relative;aspect-ratio:1/1;overflow:hidden;background:#161616;cursor:pointer}.reelo-grid-item video{width:100%;height:100%;object-fit:cover;display:block}.reelo-grid-overlay{position:absolute;inset:0;display:flex;align-items:flex-end;padding:7px;background:linear-gradient(transparent,rgba(0,0,0,.7));opacity:0;transition:.18s}.reelo-grid-item:hover .reelo-grid-overlay,.reelo-grid-item:focus .reelo-grid-overlay{opacity:1}.reelo-grid-stats{font-size:10px;font-weight:800}.reelo-grid-reel{position:absolute;top:7px;right:7px;background:rgba(0,0,0,.6);border-radius:999px;padding:4px 6px;font-size:9px}.reelo-explore-users{display:grid;gap:2px}.reelo-explore-user{display:flex;align-items:center;gap:10px;padding:10px;border-radius:12px;background:#121212}.reelo-user-avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#fff,#555);color:#000;font-weight:900}.reelo-user-meta{flex:1;min-width:0}.reelo-user-meta b{font-size:12px}.reelo-user-meta small{display:block;color:#777;font-size:10px;margin-top:2px}.reelo-follow-btn{border:0;border-radius:8px;background:#fff;color:#000;padding:7px 11px;font-size:10px;font-weight:900}.reelo-search-empty{padding:50px 10px;text-align:center;color:#777}.reelo-search-empty strong{display:block;color:#fff;font-size:16px;margin-bottom:5px}.reelo-loading{padding:35px;text-align:center;color:#777}.reelo-explore-error{padding:30px;text-align:center;color:#777}.reelo-explore-error button{margin-top:10px;border:0;border-radius:9px;background:#fff;color:#000;padding:8px 14px;font-weight:800}
  @media(max-width:380px){.reelo-topics{grid-template-columns:1fr 1fr}.reelo-explore-title{font-size:23px}}
  `;document.head.appendChild(s)}
  function header(){return '<div class="reelo-explore-hero"><div class="reelo-explore-title">Explore</div><div class="reelo-explore-sub">Discover creators, sounds, hashtags and trending videos</div></div><div class="reelo-chips"><button class="reelo-chip active" data-e="top">For you</button><button class="reelo-chip" data-e="reels">Reels</button><button class="reelo-chip" data-e="creators">Creators</button><button class="reelo-chip" data-e="hashtags">Hashtags</button></div>'}
  function topics(){return '<div class="reelo-discover-title"><b>Discover topics</b><span>Trending now</span></div><div class="reelo-topics">'+demo.map(x=>'<button class="reelo-topic" type="button" data-query="'+x[2]+'"><span class="reelo-topic-icon">'+x[0]+'</span><b>'+x[2]+'</b><small>'+x[3]+'</small></button>').join('')+'</div>'}
  function users(items){const seen=new Set(),a=[];(items||[]).forEach(v=>{const id=String(v.user_id||v.username||'');if(!id||seen.has(id))return;seen.add(id);a.push(v)});return a.slice(0,8).map(v=>'<div class="reelo-explore-user"><span class="reelo-user-avatar">'+esc((v.username||'u')[0]).toUpperCase()+'</span><span class="reelo-user-meta"><b>'+esc(v.display_name||v.username)+'</b><small>@'+esc(v.username)+'</small></span><button class="reelo-follow-btn" type="button">Follow</button></div>').join('')}
  function grid(items){return '<div class="reelo-explore-grid">'+(items||[]).slice(0,30).map(v=>'<article class="reelo-grid-item" tabindex="0"><video src="'+esc(videoUrl(v))+'" muted playsinline preload="metadata"></video><span class="reelo-grid-reel">▶ REEL</span><div class="reelo-grid-overlay"><span class="reelo-grid-stats">♥ '+fmt(v.likes)+' &nbsp; · &nbsp; ▶ '+fmt(v.views)+'</span></div></article>').join('')+'</div>'}
  function bind(){document.querySelectorAll('.reelo-chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.reelo-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');run(q.value,b.dataset.e)});document.querySelectorAll('.reelo-topic').forEach(b=>b.onclick=()=>{q.value=b.dataset.query;run(q.value,'top')});document.querySelectorAll('.reelo-grid-item video').forEach(v=>{v.addEventListener('mouseenter',()=>v.play().catch(()=>{}));v.addEventListener('mouseleave',()=>{v.pause();v.currentTime=0})})}
  async function run(query,mode){query=(query||'').trim();content.innerHTML=header()+(query?'':'<div>'+topics()+'</div>');bind();if(!query)return;content.insertAdjacentHTML('beforeend','<div class="reelo-loading">Finding the best matches…</div>');try{const token=localStorage.getItem('reelo_token');const r=await fetch(API+'/api/smart-search?q='+encodeURIComponent(query)+'&limit=30',{headers:token?{Authorization:'Bearer '+token}:{}});if(!r.ok)throw Error();const d=await r.json(),items=d.items||[];content.innerHTML=header();if(mode==='creators')content.insertAdjacentHTML('beforeend','<div class="reelo-discover-title"><b>Creators</b></div><div class="reelo-explore-users">'+users(items)+'</div>');else if(mode==='hashtags')content.insertAdjacentHTML('beforeend','<div class="reelo-discover-title"><b>Hashtags</b></div><div class="reelo-topics">'+(d.trending_hashtags||[]).slice(0,12).map(t=>'<button class="reelo-topic" type="button" data-query="'+esc(t)+'"><b>'+esc(t)+'</b><small>Trending hashtag</small></button>').join('')+'</div>');else content.insertAdjacentHTML('beforeend','<div class="reelo-discover-title"><b>'+((mode==='reels')?'Reels':'Top results')+'</b><span>'+items.length+' found</span></div>'+grid(items));bind()}catch(e){content.innerHTML=header()+'<div class="reelo-explore-error">Explore is temporarily unavailable.<br><button type="button" id="reelo-retry">Try again</button></div>';bind();document.getElementById('reelo-retry').onclick=()=>run(q.value,mode)}}
  style();q.addEventListener('input',()=>{clearTimeout(window.reeloExploreTimer);window.reeloExploreTimer=setTimeout(()=>run(q.value,'top'),250)});run('','top');
})();
