(() => {
  const input=document.getElementById('q'), content=document.getElementById('content');
  if(!input||!content)return;
  const API=window.REELO_API||'http://localhost:8000'; let timer,lastQuery='';
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>{n=Number(n||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n)};
  const videoUrl=v=>v.filename?.startsWith('http')?v.filename:API+(v.filename?.startsWith('/')?'':'/')+v.filename;
  if(!document.getElementById('smart-search-style')){const s=document.createElement('style');s.id='smart-search-style';s.textContent=`
    .smart-box{margin:10px 0 4px}.smart-label{font-size:11px;color:#777;text-transform:uppercase;letter-spacing:.08em;margin:12px 0 8px}.smart-row{display:flex;gap:8px;overflow:auto;padding-bottom:4px}.smart-chip{flex:none;border:1px solid #333;background:#151515;color:#ddd;border-radius:18px;padding:8px 11px;cursor:pointer}.smart-chip:hover{background:#242424}.smart-chip.hot:before{content:'🔥 '}.smart-chip.hash:before{content:'# ';color:#777}.smart-chip.creator:before{content:'@ ';color:#777}.smart-video{cursor:pointer;border-radius:10px;padding:10px;margin:0 -8px}.smart-video:hover{background:#151515}.smart-badge{font-size:10px;color:#777;margin-top:5px}`;document.head.appendChild(s)}
  function chips(items,cls=''){return(items||[]).slice(0,12).map(x=>`<button class="smart-chip ${cls}" data-search="${esc(x)}">${esc(x)}</button>`).join('')}
  function bind(){content.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{input.value=b.dataset.search;lastQuery='';run(input.value)});content.querySelectorAll('[data-video-id]').forEach(e=>e.onclick=()=>{location.href='/?video='+encodeURIComponent(e.dataset.videoId)})}
  function discovery(d){content.innerHTML=`<div class="smart-box"><div class="smart-label">Trending now</div><div class="smart-row">${chips(d.trending_topics,'hot')}</div><div class="smart-label">Popular hashtags</div><div class="smart-row">${chips(d.trending_hashtags,'hash')}</div><div class="smart-label">Creators to discover</div><div class="smart-row">${chips((d.trending_creators||[]).map(x=>'@'+x),'creator')}</div></div>`;bind()}
  function render(d){const items=d.items||[],sug=d.suggestions||[],topics=d.topics||[];let h='';if(sug.length)h+=`<div class="smart-box"><div class="smart-label">Suggestions</div><div class="smart-row">${chips(sug)}</div></div>`;if(topics.length)h+=`<div class="smart-box"><div class="smart-label">Detected topics</div><div class="smart-row">${chips(topics)}</div></div>`;if(items.length)h+=`<div class="section-title">Smart results</div>`+items.map((v,i)=>`<article class="video smart-video" data-video-id="${esc(v.id)}"><video class="thumb" src="${esc(videoUrl(v))}" muted playsinline preload="metadata"></video><div class="meta"><div class="name">@${esc(v.username||'creator')}</div><div class="caption">${esc(v.caption||'No caption')}</div><div class="stats">${fmt(v.likes)} likes · ${fmt(v.comments)} comments · ${fmt(v.views)} views</div><div class="smart-badge">${i<3?'Top match · ':''}${d.personalized?'Personalized ranking':'Relevance + freshness'}</div></div></article>`).join('');content.innerHTML=h||'<div class="empty">No smart results found. Try a creator, topic, or hashtag.</div>';bind()}
  async function run(value){const query=value.trim();if(!query){lastQuery='';content.innerHTML='<div class="loading">Loading discovery…</div>';try{const r=await fetch(API+'/api/smart-search');if(!r.ok)throw 0;discovery(await r.json())}catch(e){content.innerHTML='<div class="empty">Search REelo</div>'}return}if(query===lastQuery)return;lastQuery=query;content.innerHTML='<div class="loading">Finding the best matches…</div>';try{const r=await fetch(API+'/api/smart-search?q='+encodeURIComponent(query)+'&limit=30');if(!r.ok)throw 0;render(await r.json())}catch(e){content.innerHTML='<div class="empty">Smart search is temporarily unavailable.</div>'}}
  input.addEventListener('input',e=>{e.stopImmediatePropagation();clearTimeout(timer);lastQuery='';timer=setTimeout(()=>run(input.value),180)},true);
  input.addEventListener('focus',()=>{if(!input.value)run('')});run('');
})();
