(() => {
  const API=window.REELO_API||'http://localhost:8000';
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>document.getElementById(id);
  function mount(){
    if($('topicsPanel'))return;
    const st=document.createElement('style'); st.textContent='.topics-panel{position:absolute;inset:0;background:#080808;z-index:26;display:none;padding:calc(18px + env(safe-area-inset-top)) 16px 24px;overflow:auto}.topics-panel.show{display:block}.topics-head{display:flex;align-items:center;gap:12px;margin-bottom:8px}.topics-head button{border:0;background:none;color:#fff;font-size:28px}.topics-sub{color:#888;margin:0 0 18px}.topic-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.topic-tile{border:1px solid #2b2b2b;background:#151515;color:#fff;border-radius:16px;padding:18px 14px;text-align:left;min-height:100px}.topic-name{font-size:17px;font-weight:900;text-transform:capitalize}.topic-count{display:block;color:#888;font-size:12px;margin-top:8px}.topic-list{margin-top:20px}.topic-video{padding:13px 0;border-bottom:1px solid #252525;color:#fff}.topic-video b{font-size:13px}.topic-video span{display:block;color:#999;font-size:12px;margin-top:5px}'; document.head.appendChild(st);
    const p=document.createElement('section');p.id='topicsPanel';p.className='topics-panel';p.innerHTML='<div class="topics-head"><button onclick="window.closeTopics()">‹</button><h2 style="margin:0">Explore Topics</h2></div><p class="topics-sub">Discover communities and videos by interest</p><div id="topicGrid">Loading…</div><div id="topicVideos" class="topic-list"></div>';document.querySelector('.shell')?.appendChild(p);
  }
  async function openTopics(){mount();$('topicsPanel').classList.add('show');$('topicGrid').innerHTML='Loading…';$('topicVideos').innerHTML='';try{const r=await fetch(API+'/api/topics?limit=20');if(!r.ok)throw Error();const d=await r.json();const items=d.items||[];$('topicGrid').innerHTML=items.length?'<div class="topic-grid">'+items.map(x=>`<button class="topic-tile" onclick="window.openTopic('${esc(x.topic)}')"><span class="topic-name">#${esc(x.topic)}</span><span class="topic-count">${x.videos} videos</span></button>`).join('')+'</div>':'<div style="color:#777">No topics yet.</div>'}catch(e){$('topicGrid').textContent='Topics are temporarily unavailable.'}}
  async function openTopic(topic){$('topicVideos').innerHTML='Loading #'+esc(topic)+'…';try{const r=await fetch(API+'/api/topics/'+encodeURIComponent(topic)+'?limit=50');const d=await r.json();$('topicVideos').innerHTML=(d.items||[]).map(v=>`<div class="topic-video"><b>@${esc(v.username||'creator')}</b><span>${esc(v.caption||'Video')}</span></div>`).join('')||'<div style="color:#777">No videos in this topic yet.</div>'}catch(e){$('topicVideos').textContent='Unable to load topic videos.'}}
  function closeTopics(){const p=$('topicsPanel');if(p)p.classList.remove('show')}
  window.openTopics=openTopics;window.openTopic=openTopic;window.closeTopics=closeTopics;
  document.addEventListener('DOMContentLoaded',()=>{mount();const tabs=document.querySelector('.tabs');if(tabs&&!$('topicsBtn')){const b=document.createElement('button');b.id='topicsBtn';b.textContent='Topics';b.onclick=openTopics;tabs.appendChild(b)}});
})();
